name: Deploy to znam.fun v2

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create deployment package
      run: |
        # Создаем архив для деплоя
        zip -r deploy.zip . -x "node_modules/*" ".wwebjs_auth/*" ".wwebjs_cache/*" ".git/*" "*.log"
        
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: server276.hosting.reg.ru
        username: u3217624
        password: ${{ secrets.HOSTING_PASSWORD }}
        port: 22
        timeout: 30s
        command_timeout: 10m
        script: |
          echo "Starting deployment process..."
          
          # Создаем папку если её нет
          mkdir -p /var/www/u3217624/data/znam.fun
          echo "Directory created/verified"
          
          cd /var/www/u3217624/data/znam.fun
          echo "Changed to deployment directory: $(pwd)"
          
          # Останавливаем текущий процесс если он запущен
          echo "Stopping existing processes..."
          pkill -f "node server-multi.js" 2>/dev/null || true
          sleep 2
          
          # Очищаем старые файлы
          echo "Cleaning old files..."
          rm -rf *
          echo "Cleanup completed"
          
        script_stop: true
        
    - name: Upload files
      uses: appleboy/scp-action@v0.1.7
      with:
        host: server276.hosting.reg.ru
        username: u3217624
        password: ${{ secrets.HOSTING_PASSWORD }}
        port: 22
        source: "deploy.zip"
        target: "/var/www/u3217624/data/znam.fun/"
        timeout: 30s
        
    - name: Setup and start server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: server276.hosting.reg.ru
        username: u3217624
        password: ${{ secrets.HOSTING_PASSWORD }}
        port: 22
        timeout: 30s
        command_timeout: 10m
        script: |
          echo "Setting up server..."
          cd /var/www/u3217624/data/znam.fun
          echo "Current directory: $(pwd)"
          
          # Распаковываем архив
          echo "Extracting deployment package..."
          unzip -o deploy.zip
          rm -f deploy.zip
          echo "Package extracted"
          
          # Устанавливаем зависимости
          echo "Installing dependencies..."
          npm install --production
          echo "Dependencies installed"
          
          # Создаем скрипт запуска
          echo "Creating startup script..."
          cat > start.sh << 'EOF'
          #!/bin/bash
          cd /var/www/u3217624/data/znam.fun
          node server-multi.js > app.log 2>&1 &
          echo $! > app.pid
          echo "Server started with PID $(cat app.pid)"
          EOF
          
          chmod +x start.sh
          echo "Startup script created"
          
          # Запускаем сервер
          echo "Starting server..."
          ./start.sh
          
          # Проверяем что сервер запустился
          sleep 3
          if [ -f app.pid ]; then
            PID=$(cat app.pid)
            if kill -0 $PID 2>/dev/null; then
              echo "Server is running with PID $PID"
            else
              echo "Server failed to start"
              cat app.log
              exit 1
            fi
          else
            echo "PID file not created"
            exit 1
          fi
          
          # Создаем .htaccess для прокси
          cat > .htaccess << 'EOF'
          RewriteEngine On
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule ^(.*)$ http://localhost:3001/$1 [P,L]
          EOF
          
          echo "Deployment completed successfully!" 